
import { Drug, Category, CalculationType, UnitType } from './types';

export const CATEGORIES: Category[] = [
  { id: 'vasopressor', name: 'Vasopressores', color: 'bg-red-600' },
  { id: 'inotrope', name: 'Inotrópicos', color: 'bg-orange-500' },
  { id: 'vasodilator', name: 'Vasodilatadores', color: 'bg-purple-600' },
  { id: 'sedation_cont', name: 'Sedação Contínua', color: 'bg-blue-600' },
  { id: 'sedation_proc', name: 'Sedação Procedimento', color: 'bg-teal-600' },
  { id: 'iot', name: 'Drogas IOT', color: 'bg-emerald-600' },
  { id: 'blocker', name: 'Bloqueador Contínuo', color: 'bg-slate-600' },
];

export const DRUGS: Drug[] = [
  // --- VASOPRESSORES ---
  {
    id: 'noradrenalina_64',
    name: 'Noradrenalina',
    groupName: 'Noradrenalina',
    variantLabel: 'Padrão (4mg/4mL)',
    category: 'vasopressor',
    presentation: '8 mg/4 mL (4mg base)',
    dilution: '4 AMP + 234ML SF/SG5%',
    concentrationString: '64 MCG/ML',
    doseString: '0,01-2 MCG/KG/MIN',
    notes: 'Sugere-se adição de vasopressina quando dose > 0,25-0,5 mcg/kg/min.',
    type: CalculationType.Continuous,
    concentrationVal: 64,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'noradrenalina_128',
    name: 'Noradrenalina',
    groupName: 'Noradrenalina',
    variantLabel: 'Concentrada (8mg/4mL)',
    category: 'vasopressor',
    presentation: '8 mg/4 mL (4mg base)',
    dilution: '8 AMP + 218ML SF/SG5%',
    concentrationString: '128 MCG/ML',
    doseString: '0,01-2 MCG/KG/MIN',
    notes: 'Solução concentrada para restrição hídrica ou doses altas.',
    type: CalculationType.Continuous,
    concentrationVal: 128,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'dopamina',
    name: 'Dopamina',
    groupName: 'Dopamina',
    category: 'vasopressor',
    presentation: '5 mg/mL (10 mL)',
    dilution: '5 AMP + 200ML SF/SG5%',
    concentrationString: '1000 MCG/ML',
    doseString: '5 - 20 mcg/kg/min',
    notes: 'Efeito dopa: < 5 | Beta: 5-10 | Alfa: > 10 mcg/kg/min',
    type: CalculationType.Continuous,
    concentrationVal: 1000,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'adrenalina',
    name: 'Adrenalina',
    groupName: 'Adrenalina',
    category: 'vasopressor',
    presentation: '1 mg/mL (1 mL)',
    dilution: '12 AMP + 188ML SF/SG5%',
    concentrationString: '60 MCG/ML',
    doseString: '1-20 mcg/min',
    notes: 'Dose choque: 1-20 mcg/min. Anafilaxia: 0,05-0,1 mg/min.',
    type: CalculationType.Continuous,
    concentrationVal: 60,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgMin,
    isWeightBased: false // Based on PDF "mcg/min"
  },
  {
    id: 'vasopressina_02',
    name: 'Vasopressina',
    groupName: 'Vasopressina',
    variantLabel: 'Padrão (0,2 U/mL)',
    category: 'vasopressor',
    presentation: '20 U/mL',
    dilution: '1 AMP + 99ML SF/SG5%',
    concentrationString: '0,2 U/ML',
    doseString: '0,01-0,04 U/MIN',
    notes: 'Poupador de catecolaminas.',
    type: CalculationType.Continuous,
    concentrationVal: 0.2,
    concentrationUnit: 'U/ml',
    doseUnit: UnitType.UMin,
    isWeightBased: false
  },
  {
    id: 'vasopressina_04',
    name: 'Vasopressina',
    groupName: 'Vasopressina',
    variantLabel: 'Concentrada (0,4 U/mL)',
    category: 'vasopressor',
    presentation: '20 U/mL',
    dilution: '2 AMP + 98ML SF/SG5%',
    concentrationString: '0,4 U/ML',
    doseString: '0,01-0,04 U/MIN',
    notes: 'Solução concentrada.',
    type: CalculationType.Continuous,
    concentrationVal: 0.4,
    concentrationUnit: 'U/ml',
    doseUnit: UnitType.UMin,
    isWeightBased: false
  },

  // --- INOTRÓPICOS ---
  {
    id: 'dobutamina_1000',
    name: 'Dobutamina',
    groupName: 'Dobutamina',
    variantLabel: 'Padrão (1000 mcg/mL)',
    category: 'inotrope',
    presentation: '250 mg/20 mL',
    dilution: '1 AMP + 230ML SF/SG5%',
    concentrationString: '1000 MCG/ML',
    doseString: '2 - 20 mcg/kg/min',
    notes: 'Agonista β1 e β2. Doses > 20 mcg/kg/min pouco benefício.',
    type: CalculationType.Continuous,
    concentrationVal: 1000,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'dobutamina_4000',
    name: 'Dobutamina',
    groupName: 'Dobutamina',
    variantLabel: 'Concentrada (4000 mcg/mL)',
    category: 'inotrope',
    presentation: '250 mg/20 mL',
    dilution: '4 AMP + 170ML SF/SG5%',
    concentrationString: '4000 MCG/ML',
    doseString: '2 - 20 mcg/kg/min',
    type: CalculationType.Continuous,
    concentrationVal: 4000,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'milrinone',
    name: 'Milrinone',
    groupName: 'Milrinone',
    category: 'inotrope',
    presentation: '1 mg/mL (10 mL)',
    dilution: '2 AMP + 80ML SF/SG5%',
    concentrationString: '200 MCG/ML',
    doseString: '0,375 - 0,75 mcg/kg/min',
    notes: 'Inibidor fosfodiesterase. Risco de hipotensão/arritmias. Evitar em isquemia.',
    type: CalculationType.Continuous,
    concentrationVal: 200,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'levosimendana',
    name: 'Levosimendana',
    groupName: 'Levosimendana',
    category: 'inotrope',
    presentation: '2,5 mg/mL (5 mL)',
    dilution: '2 AMP + 490ML SG5%',
    concentrationString: '50 MCG/ML',
    doseString: '0,05 - 0,2 mcg/kg/min',
    notes: 'Sensibiliza troponina C. Aumenta contratilidade com baixo gasto energético.',
    type: CalculationType.Continuous,
    concentrationVal: 50,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },

  // --- VASODILATADORES ---
  {
    id: 'tridil',
    name: 'Nitroglicerina (Tridil)',
    groupName: 'Nitroglicerina (Tridil)',
    category: 'vasodilator',
    presentation: '5 mg/mL (5 mL)',
    dilution: '1 AMP (10ML) + 240ML SF/SG5%',
    concentrationString: '200 MCG/ML',
    doseString: '0,5 - 10 mcg/kg/min',
    notes: 'Titular até alívio sintomas/PA alvo. Contraindicada se uso de inibidores PDE-5.',
    type: CalculationType.Continuous,
    concentrationVal: 200,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'nipride',
    name: 'Nitroprussiato (Nipride)',
    groupName: 'Nitroprussiato (Nipride)',
    category: 'vasodilator',
    presentation: '50 mg/2 mL',
    dilution: '1 AMP + 248ML SF/SG5%',
    concentrationString: '200 MCG/ML',
    doseString: '0,3 - 10 mcg/kg/min',
    notes: 'Risco de roubo de fluxo coronário e intoxicação por cianeto.',
    type: CalculationType.Continuous,
    concentrationVal: 200,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },

  // --- SEDAÇÃO CONTÍNUA ---
  {
    id: 'midazolam_cont',
    name: 'Midazolam (Contínuo)',
    groupName: 'Midazolam (Contínuo)',
    category: 'sedation_cont',
    presentation: '50 mg/10 mL',
    dilution: '4 AMP (10ML) + 160ML SF/SG5%',
    concentrationString: '1 MG/ML',
    doseString: '0,01 a 0,1 mg/kg/h',
    type: CalculationType.Continuous,
    concentrationVal: 1,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKgH,
    isWeightBased: true
  },
  {
    id: 'propofol_cont',
    name: 'Propofol (Contínuo)',
    groupName: 'Propofol (Contínuo)',
    category: 'sedation_cont',
    presentation: '2% (20 mg/mL)',
    dilution: '5 AMPOLAS PURO',
    concentrationString: '20 MG/ML',
    doseString: '10 - 200 mcg/kg/min',
    notes: 'Concentração 2% = 20mg/mL = 20.000 mcg/mL',
    type: CalculationType.Continuous,
    concentrationVal: 20000,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  },
  {
    id: 'quetamina_cont',
    name: 'Quetamina (Contínuo)',
    groupName: 'Quetamina (Contínuo)',
    category: 'sedation_cont',
    presentation: '50 mg/mL',
    dilution: '1 AMP (10ML) + 240ML SF/SG5%',
    concentrationString: '2 MG/ML',
    doseString: '0,5-1,2 MG/KG/H',
    type: CalculationType.Continuous,
    concentrationVal: 2,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKgH,
    isWeightBased: true
  },
  {
    id: 'precedex',
    name: 'Dexmedetomidina',
    groupName: 'Dexmedetomidina',
    category: 'sedation_cont',
    presentation: '100 mcg/mL',
    dilution: '2 AMP + 96ML SF/SG5%',
    concentrationString: '4 MCG/ML',
    doseString: '0,2-1,4 MCG/KG/H',
    type: CalculationType.Continuous,
    concentrationVal: 4,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgH,
    isWeightBased: true
  },
  {
    id: 'fentanil_cont',
    name: 'Fentanil (Contínuo)',
    groupName: 'Fentanil (Contínuo)',
    category: 'sedation_cont',
    presentation: '50 mcg/ml',
    dilution: '5 AMPOLAS PURO',
    concentrationString: '50 MCG/ML',
    doseString: '0,02-0,07 MCG/KG/H',
    type: CalculationType.Continuous,
    concentrationVal: 50,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgH,
    isWeightBased: true
  },

  // --- SEDAÇÃO PROCEDIMENTO (BOLUS) ---
  {
    id: 'propofol_proc',
    name: 'Propofol (Bolus)',
    groupName: 'Propofol (Bolus)',
    category: 'sedation_proc',
    presentation: '1% (10 mg/mL)',
    dilution: 'PURO',
    concentrationString: '10 MG/mL',
    doseString: '0,5-1 mg/kg', 
    notes: 'PDF diz 0,5-1 mcg/kg, mas usualmente é mg/kg para indução. Ajustado para 0,5-1 mg/kg.',
    type: CalculationType.Bolus,
    concentrationVal: 10,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'cetamina_proc',
    name: 'Cetamina (Bolus)',
    groupName: 'Cetamina (Bolus)',
    category: 'sedation_proc',
    presentation: '50 mg/mL',
    dilution: 'PURO',
    concentrationString: '50 MG/ML',
    doseString: '0,5-1 MG/KG',
    notes: '0,25 a 0,5 mg/kg podem ser usadas a cada 5-10min.',
    type: CalculationType.Bolus,
    concentrationVal: 50,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'ketofol',
    name: 'Ketofol',
    groupName: 'Ketofol',
    category: 'sedation_proc',
    presentation: 'Mix',
    dilution: '2ML Quetamina + 10ML Propofol + 8ML AD/SF',
    concentrationString: '5mg/ml propofol : 5mg/ml cetamina',
    doseString: '0,5 a 1 mg/kg',
    notes: 'Fazer 0,5 a 1 mL para cada 10kg.',
    type: CalculationType.Bolus,
    concentrationVal: 10,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'ketodex',
    name: 'Ketodex',
    groupName: 'Ketodex',
    category: 'sedation_proc',
    presentation: 'Mix',
    dilution: '2ML QUETAMINA + 1ML PRECEDEX + 17ML AD/SF',
    concentrationString: '5mg/ml cetamina : 5mcg/ml precedex',
    doseString: '1 a 2 mL da solução a cada 5 kg',
    notes: 'Equivalência: 1 mL da solução/5kg = 1 mg/kg de Cetamina + 1 mcg/kg de Precedex. Para cálculo na ferramenta, utilize a dose em mg/kg (1-2).',
    type: CalculationType.Bolus,
    concentrationVal: 5,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },

  // --- DROGAS IOT ---
  {
    id: 'fentanil_iot',
    name: 'Fentanil (IOT)',
    groupName: 'Fentanil (IOT)',
    category: 'iot',
    presentation: '50 mcg/mL',
    dilution: 'PURO',
    concentrationString: '50 MCG/ML',
    doseString: '1-3 MCG/KG',
    notes: 'Indicado na crise hipertensiva / SCA / HIC / Dissecção.',
    type: CalculationType.Bolus,
    concentrationVal: 50,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKg,
    isWeightBased: true
  },
  {
    id: 'lidocaina_iot',
    name: 'Lidocaína 2%',
    groupName: 'Lidocaína 2%',
    category: 'iot',
    presentation: '20 mg/mL',
    dilution: 'PURO',
    concentrationString: '20 MG/ML',
    doseString: '1,5 MG/KG',
    type: CalculationType.Bolus,
    concentrationVal: 20,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'etomidato',
    name: 'Etomidato',
    groupName: 'Etomidato',
    category: 'iot',
    presentation: '2 mg/mL',
    dilution: 'PURO',
    concentrationString: '2 MG/ML',
    doseString: '0,3 MG/KG',
    notes: 'Cardioestável. Supressão adrenal transitória.',
    type: CalculationType.Bolus,
    concentrationVal: 2,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'midazolam_iot',
    name: 'Midazolam (IOT)',
    groupName: 'Midazolam (IOT)',
    category: 'iot',
    presentation: '5 mg/mL',
    dilution: 'PURO',
    concentrationString: '5 MG/ML',
    doseString: '0,1-0,3 MG/KG',
    notes: 'Hipotensor. Contraindicado em glaucoma de ângulo fechado.',
    type: CalculationType.Bolus,
    concentrationVal: 5,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'succinilcolina',
    name: 'Succinilcolina',
    groupName: 'Succinilcolina',
    category: 'iot',
    presentation: '100mg/frasco',
    dilution: '1 Frasco + 10mL AD',
    concentrationString: '10 MG/ML',
    doseString: '1-1,5 MG/KG',
    notes: 'Muitas contraindicações (Hipercalemia, Queimados, AVC < 3 dias, etc).',
    type: CalculationType.Bolus,
    concentrationVal: 10,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },
  {
    id: 'rocuronio_iot',
    name: 'Rocurônio (Bolus)',
    groupName: 'Rocurônio (Bolus)',
    category: 'iot',
    presentation: '10 mg/mL',
    dilution: 'PURO',
    concentrationString: '10 MG/ML',
    doseString: '1,2 MG/KG',
    notes: 'Antídoto: Sugamadex.',
    type: CalculationType.Bolus,
    concentrationVal: 10,
    concentrationUnit: 'mg/ml',
    doseUnit: UnitType.MgKg,
    isWeightBased: true
  },

  // --- BLOQUEADOR CONTÍNUO ---
  {
    id: 'rocuronio_cont',
    name: 'Rocurônio (Contínuo)',
    groupName: 'Rocurônio (Contínuo)',
    category: 'blocker',
    presentation: '10 mg/mL',
    dilution: '5 AMP + 225ML SF/SG5%',
    concentrationString: '10000 MCG/ML',
    doseString: '8-12 MCG/KG/MIN',
    type: CalculationType.Continuous,
    concentrationVal: 10000,
    concentrationUnit: 'mcg/ml',
    doseUnit: UnitType.McgKgMin,
    isWeightBased: true
  }
];
